### PR TITLE
Remove FillArrays dependency

### PR DESCRIPTION
**Pull request by willtebbutt**
Supercedes #96 

It appears that Kronecker.jl wasn't actually using FillArrays.jl, so I've removed the dependency.

@MichielStock (assuming that I've not missed something) are you alright with this?

### CODE REVIEW

**Comment by elisno** [comment]
FillArrays.jl exports `Eye`, which is only used during testing: https://github.com/MichielStock/Kronecker.jl/blob/4967a5f291b2e4f3210ae4f3c073e7d5478d79ee/test/testmultiply.jl#L74-L81

**Comment by willtebbutt** [comment]
Ah, damn, not sure how I missed that when running tests. I'll add it back in as a test dep.

**Comment by elisno** [comment]
Wouldn't it be sufficient to add this to `test/Project.toml` (along with other test-specific dependencies)?

**Comment by willtebbutt** [comment]
I would, but unfortunately that won't work on Julia versions pre 1.3 (or maybe 1.2?), and this package currently supports version 1.0.

**Comment by MichielStock** [comment]
I guess we can replace `Eye` by `Matric(I, n)` to remove the dependency completely?

Otherwise, I will merge.

**Comment by willtebbutt** [comment]
> I guess we can replace Eye by Matric(I, n) to remove the dependency completely?

Excellent. I'll do that now.

**Comment by willtebbutt** [comment]
@MichielStock ready for review -- there are no FillArrays dependencies anywhere in the package now.

**Comment by dkarrasch** [comment]
How about replacing `Eye(n)` with `I(n)` to get a `Diagonal`? That syntax has a lower bound of Julia v1.2, though.

**Comment by willtebbutt** [comment]
I'm happy to go with @MichielStock would prefer. I suppose it depends on how attached he is to 1.0 compatibility.

**Comment by dkarrasch** [comment]
Ah, if it's only used for testing, then there is no need to aim for efficiency. Sorry for the noise.

**Comment by willtebbutt** [comment]
@MichielStock are you happy to merge this?

**Comment by MichielStock** [comment]
Yes! Tested it but forgot to merge it.

**Pull request merged**
