### PR TITLE
Resolve ambiguity in multiplying Diagonal kronecker products

### PR DESCRIPTION
**Pull request by jishnub**
Fixes the following multiplications:

```julia
julia> A = randn(4, 4);

julia> B = Array{Float64, 2}([1 2 3;
                4 5 6;
                7 -2 9]);

julia> K = A ⊗ B;

julia> Kd = Diagonal(A) ⊗ Diagonal(B);

julia> Kd2 = Diagonal(B) ⊗ Diagonal(A);

julia> Kd * Kd2 ≈ Diagonal(Kd) * Diagonal(Kd2)
true

julia> Kd2 * Kd ≈ Diagonal(Kd2) * Diagonal(Kd)
true

julia> K * Kd ≈ collect(K) * Diagonal(Kd)
true

julia> Kd * K ≈ Diagonal(Kd) * collect(K)
true
```

### CODE REVIEW

**Comment by MichielStock** [comment]
I've noticed that `Diagonal(K)` returns are regular `Diagonal` matrix rather than a `KronProdDiagonal`. Would it make sence to also extend this function a la 

```julia
LinearAlgebra.Diagonal(K::AbstractKronecker) = mapreduce(Diagonal, ⊗, getmatrices(K))
```

**Comment by jishnub** [comment]
`Diagonal` refers to the constructor, therefore it should return an object of the same type. Perhaps we may add a function `diagonal` to `Kronecker` that will return the appropriate type? Ideally there could have been such a function in `LinearAlgebra` that we may overload here, but as of now there's only the constructor that exists.

**Comment by MichielStock** [comment]
For many cases, the difference between a diagonal or a Kronecker type might be minimal. Though it might be useful to add two Kronecker produces?

Agreed that we should not mess with constructors! `LinearAlgebra.diagm` might fit the bill though.

**Comment by jishnub** [comment]
`diagm` constructs a matrix given the vector that corresponds to the diagonal. Perhaps we're looking for something like `diagm ∘ diag`, but at that point it's probably easier to define our own function

**Comment by MichielStock** [comment]
You are right, my bad! I thought it also created a diagonal matrix from a square matrix. If we agree that we want the behaviour as discussed, I am in favor of our own function

```julia
diagonal(A::AbstractMatrix) = Diagonal(A)
diagonal(K::AbstractKroneckerProduct) = mapreduce(Diagonal, ⊗, getmatrices(K))
```

**Pull request merged**
