### PR TITLE
Added willtebbutt's suggestions to #28

### PR DESCRIPTION
**Pull request by elisno**

### CODE REVIEW

**Comment by elisno** [comment]
@willtebbutt, is this enough?

**Comment by willtebbutt** [comment]
LGTM :)

**Comment by willtebbutt** [comment]
Actually, would you mind adding an extra test for `issymmetric`? Doesn't appear to be tested according to the coverage report. Might as well deal with it now.

**Comment by elisno** [comment]
The `issymmetric` tests may have been overkill.

@MichielStock: Everything passes on Travis CI. Should I squash/rebase and force-push this before merging?

**Comment by elisno** [comment]
Closing this PR since the majority of features have already been pushed to MichielStock/Kronecker.jl#28

**Pull request closed without merging**
